# -*- coding: utf-8 -*-
"""Copia de app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lm2XH0EZxY9BsGQuz86rHTEPk9li0Ymc
"""

# app.py - Predicción de Pérdida de Clientes Bancarios
# app.py - Predicción de Fuga de Clientes Bancarios

import streamlit as st
import pandas as pd
import joblib
import shap
import matplotlib.pyplot as plt
import sys
import os

# --------------------
# Importar Winsorizer para que joblib pueda cargarlo
# --------------------
sys.path.append(os.path.abspath("C:/Workspace/Proy. Perdida clientes/02_src"))
from winsorizer import Winsorizer

# --------------------
# Cargar modelo y scaler
# --------------------
@st.cache_resource
def cargar_modelo_y_scaler():
    modelo = joblib.load("05_ml_project/modelo_fuga_clientes.pkl")
    scaler = joblib.load("05_ml_project/scaler_robust_fuga_clientes.pkl")
    return modelo, scaler

modelo, scaler = cargar_modelo_y_scaler()

# --------------------
# Configuración de la app
# --------------------
st.set_page_config(page_title="Predicción Fuga Clientes", layout="centered")
st.title("📊 Predicción de Fuga de Clientes Bancarios")
st.markdown("Completa el formulario con los datos del cliente para estimar la probabilidad de abandono.")

# --------------------
# Explicación de campos del formulario
# --------------------
with st.expander("📝 Explicación de los campos del formulario"):
    st.markdown("""
    **Campos requeridos para predicción individual:**

    - `Credit Score`: Puntuación crediticia del cliente (300–900).
    - `Gender`: Género del cliente (Male / Female).
    - `Age`: Edad en años.
    - `Tenure`: Años que lleva como cliente del banco.
    - `Balance`: Saldo actual en cuenta (€).
    - `NumOfProducts`: Número de productos bancarios contratados (1 a 4).
    - `HasCrCard`: ¿Tiene tarjeta de crédito? (1 = Sí, 0 = No).
    - `IsActiveMember`: ¿Es un cliente activo? (1 = Sí, 0 = No).
    - `EstimatedSalary`: Salario estimado del cliente (€).
    - `Geography`: País de residencia (France, Germany, Spain).
    """)

# --------------------
# Leyenda general del dataset original
# --------------------
with st.expander("📚 Leyenda de todas las columnas del dataset original"):
    st.markdown("""
    | **Columna**        | **Descripción** |
    |--------------------|------------------|
    | `RowNumber`        | Número de fila del cliente |
    | `CustomerId`       | Identificador único del cliente |
    | `Surname`          | Apellido del cliente |
    | `CreditScore`      | Puntuación crediticia |
    | `Geography`        | País de residencia (Francia, España, Alemania) |
    | `Gender`           | Género (Male / Female) |
    | `Age`              | Edad |
    | `Tenure`           | Años como cliente |
    | `Balance`          | Saldo en cuenta |
    | `NumOfProducts`    | Número de productos contratados |
    | `HasCrCard`        | ¿Tiene tarjeta de crédito? (1 = Sí, 0 = No) |
    | `IsActiveMember`   | ¿Es cliente activo? (1 = Sí, 0 = No) |
    | `EstimatedSalary`  | Salario estimado |
    | `Exited`           | ¿El cliente se ha ido? (1 = Sí, 0 = No) |
    """)

# --------------------
# Formulario de entrada
# --------------------
with st.form("formulario_cliente"):
    credit_score = st.number_input("Credit Score", min_value=300, max_value=900, value=650)
    gender = st.radio("Género", ["Male", "Female"])
    age = st.slider("Edad", 18, 90, 40)
    tenure = st.selectbox("Antigüedad (años)", list(range(0, 11)))
    balance = st.number_input("Balance (€)", min_value=0, max_value=300000, value=50000, step=1000)
    num_products = st.selectbox("Número de productos bancarios", [1, 2, 3, 4])
    has_cr_card = st.radio("¿Tiene tarjeta de crédito?", [1, 0])
    is_active_member = st.radio("¿Es cliente activo?", [1, 0])
    estimated_salary = st.number_input("Salario estimado (€)", min_value=0, max_value=300000, value=50000, step=1000)
    geography = st.selectbox("Geografía", ["France", "Germany", "Spain"])

    submit = st.form_submit_button("Predecir Fuga")

# --------------------
# Procesar y mostrar resultados
# --------------------
if submit:
    geo_map = {"France": [0, 0], "Germany": [1, 0], "Spain": [0, 1]}
    geo_germany, geo_spain = geo_map[geography]
    gender_val = 1 if gender == "Male" else 0

    input_data = pd.DataFrame([[credit_score, gender_val, age, tenure, balance, num_products,
                                 has_cr_card, is_active_member, estimated_salary,
                                 geo_germany, geo_spain]],
        columns=[
            "CreditScore", "Gender", "Age", "Tenure", "Balance", "NumOfProducts",
            "HasCrCard", "IsActiveMember", "EstimatedSalary", "Geography_Germany", "Geography_Spain"
        ]
    )

    # Escalar todo el input (como en el entrenamiento)
    input_scaled = scaler.transform(input_data)
    input_data = pd.DataFrame(input_scaled, columns=input_data.columns)

    # Predicción
    prob_fuga = modelo.predict_proba(input_data)[0][1]
    prediccion = modelo.predict(input_data)[0]

    st.subheader("🔍 Resultado de la Predicción")
    st.metric(label="Probabilidad de Fuga", value=f"{prob_fuga:.2%}")
    if prediccion == 1:
        st.error("⚠️ El cliente probablemente **abandonará** el banco.")
    else:
        st.success("✅ El cliente probablemente **se quedará**.")

